# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=255)),
                ('enabled', models.CharField(max_length=2)),
                ('ctime', models.DateField()),
            ],
        ),
    ]
