# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='active',
            new_name='is_active',
        ),
    ]
