# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20171127_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='enabled',
        ),
    ]
