# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20171127_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Region'),
        ),
    ]
