# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.IntegerField(default='2018011000')),
                ('ttl', models.IntegerField(default='300')),
                ('root_name', models.CharField(default='root.conrey.us', max_length=255)),
                ('refresh', models.IntegerField(default='28880')),
                ('retry', models.IntegerField(default='3600')),
                ('expire', models.IntegerField(default='86400')),
                ('minimum', models.IntegerField(default='3600')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nameserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ttl', models.IntegerField(default=300)),
                ('content', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_type', to='domains.RecordType'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='nameserver1', to='domains.Nameserver'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver2',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='nameserver2', to='domains.Nameserver'),
        ),
        migrations.AddField(
            model_name='domain',
            name='owner',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='domain_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
