# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20171127_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ttl',
            field=models.IntegerField(default=300),
        ),
    ]
