# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20171127_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_type', to='domains.RecordType'),
        ),
    ]
