# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20171127_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='serial_number',
            field=models.IntegerField(default='2017112700'),
        ),
    ]
