# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_domain_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='id',
        ),
        migrations.AlterField(
            model_name='domain',
            name='serial_number',
            field=models.IntegerField(default='2017112700', primary_key=True, serialize=False),
        ),
    ]
