# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0007_auto_20171127_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
