# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0008_auto_20171127_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='expire',
            field=models.IntegerField(default='86400'),
        ),
        migrations.AddField(
            model_name='domain',
            name='minimum',
            field=models.IntegerField(default='3600'),
        ),
        migrations.AddField(
            model_name='domain',
            name='refresh',
            field=models.IntegerField(default='28880'),
        ),
        migrations.AddField(
            model_name='domain',
            name='retry',
            field=models.IntegerField(default='3600'),
        ),
    ]
