# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_auto_20171127_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='serial_number',
            field=models.IntegerField(default='2017112800'),
        ),
    ]
