# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0011_domain_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='root_name',
            field=models.CharField(default='root.<django.db.models.fields.CharField>', max_length=255),
        ),
    ]
