# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_domain_root_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='root_name',
            field=models.CharField(default='root.conrey.us', max_length=255),
        ),
    ]
