# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0013_auto_20171128_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ttl',
            field=models.IntegerField(default='300'),
        ),
    ]
