# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0014_domain_ttl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nameserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
