# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20171127_0104'),
        ('domains', '0015_nameserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserver',
            name='server',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='servers.Server'),
        ),
    ]
