# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0016_nameserver_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='nameserver1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='nameserver1', to='domains.Nameserver'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver2',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='nameserver2', to='domains.Nameserver'),
        ),
    ]
