# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0019_auto_20171128_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
